### PR TITLE
Update welcome-to-d.md

### PR DESCRIPTION
**Pull request by csantander**
Minor touch ups / pequeños retoques

### CODE REVIEW

**Comment by wilzbach** [comment]
CC @dlang-tour/spanish 

@csantander I think currently the Spanish translation is a bit shorthanded, so I sent out an invitation to you in case @Gehrs has no time to review ;-)

**Comment by csantander** [comment]
@wilzbach: Thanks. I'll try to continue contributing.

**Comment by csantander** [comment]
@wilzbach I was hoping someone could proof read before merging my changes, but I guess I'll just go ahead and do it myself. What's the right way to merge, though: Create a merge commit, Squash and merge, or Rebase and merge?

**Comment by wilzbach** [comment]
> @wilzbach I was hoping someone could proof read before merging my changes

Yeah I was hoping so as well. If you happen to meet other D-enthusiasts, please feel always free to ping me for adding them to your Spanish translation team!

> but I guess I'll just go ahead and do it myself. 

Yes, please do.

> What's the right way to merge, though: Create a merge commit, Squash and merge, or Rebase and merge?

There is no "right" way - all three are fine.
I usually use a Merge commit if there's only one commit and a Squash and merge operation if there are multiple commits on a PR (there is normally no need to retain this individual history).

**Pull request merged**
