### PR TITLE
Translated functions, structs and arrays into Spanish

### PR DESCRIPTION
**Pull request by diegolgz**

### CODE REVIEW

**Comment by csantander** [comment]
@wilzbach I would merge this if it wasn't for the failed build. Thoughts?

**Comment by wilzbach** [comment]
> Invalid link given: basics/delegates

The fix is quite easy: create the file (can just be a copy/paste from the English version).

**Comment by wilzbach** [comment]
BTW you can run this locally with `dub run dlang-bot -- -l . --sanitycheck`

**Comment by diegolgz** [comment]
At last! Sorry for those annoying errors.

**Comment by wilzbach** [comment]
> Fix line length in source code

BTW that has been added by the author of the dlang-tour to make the tour easier to browse on mobile devices. I have since seen that it's quite a pain and not fully convinced about this (especially because the examples look a bit weird on the desktop).

As a workaround I have added `:fullWidth` a few weeks ago, (can be used like `SourceCode:fullWidth`) for optional "opt-out" of this feature. We could also drop this feature all together, but that would probably require a bit of a discussion here https://github.com/dlang-tour/core

**Pull request merged**
